import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import { getAllPosts } from "@component/utils/posts";
import Layout from "@component/components/layout";
import CardList from "@component/components/cardList";
import styles from "@component/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ postData }) {
  // console.log(postData);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Layout>
          <h1>Hello World!</h1>
          {/* importare immagine da locale: */}
          {/* <Image
            src={process.env.PUBLIC_URL + "images/sfondo.jpg"}
            width={400}
            height={300}
            priority
            alt={"background-image"}
          /> */}
          <CardList postData={postData} />
        </Layout>
      </main>
    </>
  );
}

export const getStaticProps = () => {
  const postData = getAllPosts();
  return {
    props: {
      postData,
    },
  };
};
